### ISSUE TITLE
Фильтровать события steps/status/to_mentor

### ISSUE THREAD

**Issue by kushedow** [observer-pro/observer_back#13]
Проблема: при отправке событий steps/status/to_mentor учениками при большом количестве учеников фронт преподавателя заваливается однотипными неинформативными противным ивентами. 

Что делаем: при получении нового ивента от ученика на сервер, проверяем , отличается ли прошлый набор статусов от нового. Если да – отправляем преподавателю, если нет – не отправляем. 

**Пример 1**

Первый
{
    "1": "DONE",
    "2": "HELP",
    "3": "NONE",
    "4": "DONE"
}
Второй:

{
    "1": "DONE",
    "2": "HELP",
    "3": "NONE",
    "4": "DONE"
}

Решение: НЕ ОТПРАВЛЯЕМ

**Пример 2:**

Первый
{
    "1": "DONE",
    "2": "HELP",
    "3": "NONE",
    "4": "DONE"
}
Второй:

{
    "1": "DONE",
    "2": "HELP",
    "3": "DONE",
    "4": "DONE"
}

Решение: ОТПРАВЛЯЕМ

---

Как реализовать: при получении нового события сравниваем старый словарь с полученным, если они отличаются – перезаписываем и эмитим событие. Если нет – то нет.

**Comment by bendenko-v** [comment]
Решено!
